// Code generated by girgen. DO NOT EDIT.

package handy

import (
	"runtime"
	"unsafe"

	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gtk/v3"
)

// #cgo pkg-config: libhandy-1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <glib-object.h>
// #include <handy.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.hdy_swipe_tracker_get_type()), F: marshalSwipeTrackerer},
	})
}

type SwipeTracker struct {
	*externglib.Object

	gtk.Orientable
}

func wrapSwipeTracker(obj *externglib.Object) *SwipeTracker {
	return &SwipeTracker{
		Object: obj,
		Orientable: gtk.Orientable{
			Object: obj,
		},
	}
}

func marshalSwipeTrackerer(p uintptr) (interface{}, error) {
	return wrapSwipeTracker(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewSwipeTracker: create a new SwipeTracker object on widget.
//
// The function takes the following parameters:
//
//    - swipeable to add the tracker on.
//
func NewSwipeTracker(swipeable Swipeabler) *SwipeTracker {
	var _arg1 *C.HdySwipeable    // out
	var _cret *C.HdySwipeTracker // in

	_arg1 = (*C.HdySwipeable)(unsafe.Pointer(swipeable.Native()))

	_cret = C.hdy_swipe_tracker_new(_arg1)
	runtime.KeepAlive(swipeable)

	var _swipeTracker *SwipeTracker // out

	_swipeTracker = wrapSwipeTracker(externglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _swipeTracker
}

// AllowLongSwipes: whether to allow swiping for more than one snap point at a
// time. If the value is FALSE, each swipe can only move to the adjacent snap
// points.
func (self *SwipeTracker) AllowLongSwipes() bool {
	var _arg0 *C.HdySwipeTracker // out
	var _cret C.gboolean         // in

	_arg0 = (*C.HdySwipeTracker)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_swipe_tracker_get_allow_long_swipes(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// AllowMouseDrag: get whether self can be dragged with mouse pointer.
func (self *SwipeTracker) AllowMouseDrag() bool {
	var _arg0 *C.HdySwipeTracker // out
	var _cret C.gboolean         // in

	_arg0 = (*C.HdySwipeTracker)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_swipe_tracker_get_allow_mouse_drag(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Enabled: get whether self is enabled. When it's not enabled, no events will
// be processed. Generally widgets will want to expose this via a property.
func (self *SwipeTracker) Enabled() bool {
	var _arg0 *C.HdySwipeTracker // out
	var _cret C.gboolean         // in

	_arg0 = (*C.HdySwipeTracker)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_swipe_tracker_get_enabled(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Reversed: get whether self is reversing the swipe direction.
func (self *SwipeTracker) Reversed() bool {
	var _arg0 *C.HdySwipeTracker // out
	var _cret C.gboolean         // in

	_arg0 = (*C.HdySwipeTracker)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_swipe_tracker_get_reversed(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Swipeable: get self's swipeable widget.
func (self *SwipeTracker) Swipeable() Swipeabler {
	var _arg0 *C.HdySwipeTracker // out
	var _cret *C.HdySwipeable    // in

	_arg0 = (*C.HdySwipeTracker)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_swipe_tracker_get_swipeable(_arg0)
	runtime.KeepAlive(self)

	var _swipeable Swipeabler // out

	{
		objptr := unsafe.Pointer(_cret)
		if objptr == nil {
			panic("object of type handy.Swipeabler is nil")
		}

		object := externglib.Take(objptr)
		rv, ok := (externglib.CastObject(object)).(Swipeabler)
		if !ok {
			panic("object of type " + object.TypeFromInstance().String() + " is not handy.Swipeabler")
		}
		_swipeable = rv
	}

	return _swipeable
}

// SetAllowLongSwipes sets whether to allow swiping for more than one snap point
// at a time. If the value is FALSE, each swipe can only move to the adjacent
// snap points.
//
// The function takes the following parameters:
//
//    - allowLongSwipes: whether to allow long swipes.
//
func (self *SwipeTracker) SetAllowLongSwipes(allowLongSwipes bool) {
	var _arg0 *C.HdySwipeTracker // out
	var _arg1 C.gboolean         // out

	_arg0 = (*C.HdySwipeTracker)(unsafe.Pointer(self.Native()))
	if allowLongSwipes {
		_arg1 = C.TRUE
	}

	C.hdy_swipe_tracker_set_allow_long_swipes(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(allowLongSwipes)
}

// SetAllowMouseDrag: set whether self can be dragged with mouse pointer. This
// should usually be FALSE.
//
// The function takes the following parameters:
//
//    - allowMouseDrag: whether to allow mouse dragging.
//
func (self *SwipeTracker) SetAllowMouseDrag(allowMouseDrag bool) {
	var _arg0 *C.HdySwipeTracker // out
	var _arg1 C.gboolean         // out

	_arg0 = (*C.HdySwipeTracker)(unsafe.Pointer(self.Native()))
	if allowMouseDrag {
		_arg1 = C.TRUE
	}

	C.hdy_swipe_tracker_set_allow_mouse_drag(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(allowMouseDrag)
}

// SetEnabled: set whether self is enabled. When it's not enabled, no events
// will be processed. Usually widgets will want to expose this via a property.
//
// The function takes the following parameters:
//
//    - enabled: whether to enable to swipe tracker.
//
func (self *SwipeTracker) SetEnabled(enabled bool) {
	var _arg0 *C.HdySwipeTracker // out
	var _arg1 C.gboolean         // out

	_arg0 = (*C.HdySwipeTracker)(unsafe.Pointer(self.Native()))
	if enabled {
		_arg1 = C.TRUE
	}

	C.hdy_swipe_tracker_set_enabled(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(enabled)
}

// SetReversed: set whether to reverse the swipe direction. If self is
// horizontal, can be used for supporting RTL text direction.
//
// The function takes the following parameters:
//
//    - reversed: whether to reverse the swipe direction.
//
func (self *SwipeTracker) SetReversed(reversed bool) {
	var _arg0 *C.HdySwipeTracker // out
	var _arg1 C.gboolean         // out

	_arg0 = (*C.HdySwipeTracker)(unsafe.Pointer(self.Native()))
	if reversed {
		_arg1 = C.TRUE
	}

	C.hdy_swipe_tracker_set_reversed(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(reversed)
}

// ShiftPosition: move the current progress value by delta. This can be used to
// adjust the current position if snap points move during the gesture.
//
// The function takes the following parameters:
//
//    - delta: position delta.
//
func (self *SwipeTracker) ShiftPosition(delta float64) {
	var _arg0 *C.HdySwipeTracker // out
	var _arg1 C.gdouble          // out

	_arg0 = (*C.HdySwipeTracker)(unsafe.Pointer(self.Native()))
	_arg1 = C.gdouble(delta)

	C.hdy_swipe_tracker_shift_position(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(delta)
}

// ConnectBeginSwipe: this signal is emitted when a possible swipe is detected.
//
// The direction value can be used to restrict the swipe to a certain direction.
func (self *SwipeTracker) ConnectBeginSwipe(f func(direction NavigationDirection, direct bool)) externglib.SignalHandle {
	return self.Connect("begin-swipe", f)
}

// ConnectEndSwipe: this signal is emitted as soon as the gesture has stopped.
func (self *SwipeTracker) ConnectEndSwipe(f func(duration int64, to float64)) externglib.SignalHandle {
	return self.Connect("end-swipe", f)
}

// ConnectUpdateSwipe: this signal is emitted every time the progress value
// changes.
func (self *SwipeTracker) ConnectUpdateSwipe(f func(progress float64)) externglib.SignalHandle {
	return self.Connect("update-swipe", f)
}
