// Code generated by girgen. DO NOT EDIT.

package handy

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/atk"
	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gtk/v3"
	"github.com/diamondburned/gotk4/pkg/pango"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <handy.h>
import "C"

// glib.Type values for hdy-view-switcher.go.
var GTypeViewSwitcher = externglib.Type(C.hdy_view_switcher_get_type())

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: GTypeViewSwitcher, F: marshalViewSwitcher},
	})
}

// ViewSwitcherOverrider contains methods that are overridable.
type ViewSwitcherOverrider interface {
}

type ViewSwitcher struct {
	_ [0]func() // equal guard
	gtk.Bin
}

var (
	_ gtk.Binner = (*ViewSwitcher)(nil)
)

func classInitViewSwitcherer(gclassPtr, data C.gpointer) {
	C.g_type_class_add_private(gclassPtr, C.gsize(unsafe.Sizeof(uintptr(0))))

	goffset := C.g_type_class_get_instance_private_offset(gclassPtr)
	*(*C.gpointer)(unsafe.Add(unsafe.Pointer(gclassPtr), goffset)) = data

}

func wrapViewSwitcher(obj *externglib.Object) *ViewSwitcher {
	return &ViewSwitcher{
		Bin: gtk.Bin{
			Container: gtk.Container{
				Widget: gtk.Widget{
					InitiallyUnowned: externglib.InitiallyUnowned{
						Object: obj,
					},
					Object: obj,
					ImplementorIface: atk.ImplementorIface{
						Object: obj,
					},
					Buildable: gtk.Buildable{
						Object: obj,
					},
				},
			},
		},
	}
}

func marshalViewSwitcher(p uintptr) (interface{}, error) {
	return wrapViewSwitcher(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewViewSwitcher creates a new ViewSwitcher widget.
//
// The function returns the following values:
//
//    - viewSwitcher: new ViewSwitcher.
//
func NewViewSwitcher() *ViewSwitcher {
	var _cret *C.GtkWidget // in

	_cret = C.hdy_view_switcher_new()

	var _viewSwitcher *ViewSwitcher // out

	_viewSwitcher = wrapViewSwitcher(externglib.Take(unsafe.Pointer(_cret)))

	return _viewSwitcher
}

// NarrowEllipsize: get the ellipsizing position of the narrow mode label. See
// hdy_view_switcher_set_narrow_ellipsize().
//
// The function returns the following values:
//
//    - ellipsizeMode: EllipsizeMode.
//
func (self *ViewSwitcher) NarrowEllipsize() pango.EllipsizeMode {
	var _arg0 *C.HdyViewSwitcher   // out
	var _cret C.PangoEllipsizeMode // in

	_arg0 = (*C.HdyViewSwitcher)(unsafe.Pointer(externglib.InternObject(self).Native()))

	_cret = C.hdy_view_switcher_get_narrow_ellipsize(_arg0)
	runtime.KeepAlive(self)

	var _ellipsizeMode pango.EllipsizeMode // out

	_ellipsizeMode = pango.EllipsizeMode(_cret)

	return _ellipsizeMode
}

// Policy gets the policy of self.
//
// The function returns the following values:
//
//    - viewSwitcherPolicy: policy of self.
//
func (self *ViewSwitcher) Policy() ViewSwitcherPolicy {
	var _arg0 *C.HdyViewSwitcher      // out
	var _cret C.HdyViewSwitcherPolicy // in

	_arg0 = (*C.HdyViewSwitcher)(unsafe.Pointer(externglib.InternObject(self).Native()))

	_cret = C.hdy_view_switcher_get_policy(_arg0)
	runtime.KeepAlive(self)

	var _viewSwitcherPolicy ViewSwitcherPolicy // out

	_viewSwitcherPolicy = ViewSwitcherPolicy(_cret)

	return _viewSwitcherPolicy
}

// Stack: get the Stack being controlled by the ViewSwitcher.
//
// See: hdy_view_switcher_set_stack().
//
// The function returns the following values:
//
//    - stack (optional) or NULL if none has been set.
//
func (self *ViewSwitcher) Stack() *gtk.Stack {
	var _arg0 *C.HdyViewSwitcher // out
	var _cret *C.GtkStack        // in

	_arg0 = (*C.HdyViewSwitcher)(unsafe.Pointer(externglib.InternObject(self).Native()))

	_cret = C.hdy_view_switcher_get_stack(_arg0)
	runtime.KeepAlive(self)

	var _stack *gtk.Stack // out

	if _cret != nil {
		{
			obj := externglib.Take(unsafe.Pointer(_cret))
			_stack = &gtk.Stack{
				Container: gtk.Container{
					Widget: gtk.Widget{
						InitiallyUnowned: externglib.InitiallyUnowned{
							Object: obj,
						},
						Object: obj,
						ImplementorIface: atk.ImplementorIface{
							Object: obj,
						},
						Buildable: gtk.Buildable{
							Object: obj,
						},
					},
				},
			}
		}
	}

	return _stack
}

// SetNarrowEllipsize: set the mode used to ellipsize the text in narrow mode if
// there is not enough space to render the entire string.
//
// The function takes the following parameters:
//
//    - mode: EllipsizeMode.
//
func (self *ViewSwitcher) SetNarrowEllipsize(mode pango.EllipsizeMode) {
	var _arg0 *C.HdyViewSwitcher   // out
	var _arg1 C.PangoEllipsizeMode // out

	_arg0 = (*C.HdyViewSwitcher)(unsafe.Pointer(externglib.InternObject(self).Native()))
	_arg1 = C.PangoEllipsizeMode(mode)

	C.hdy_view_switcher_set_narrow_ellipsize(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(mode)
}

// SetPolicy sets the policy of self.
//
// The function takes the following parameters:
//
//    - policy: new policy.
//
func (self *ViewSwitcher) SetPolicy(policy ViewSwitcherPolicy) {
	var _arg0 *C.HdyViewSwitcher      // out
	var _arg1 C.HdyViewSwitcherPolicy // out

	_arg0 = (*C.HdyViewSwitcher)(unsafe.Pointer(externglib.InternObject(self).Native()))
	_arg1 = C.HdyViewSwitcherPolicy(policy)

	C.hdy_view_switcher_set_policy(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(policy)
}

// SetStack sets the Stack to control.
//
// The function takes the following parameters:
//
//    - stack (optional): Stack.
//
func (self *ViewSwitcher) SetStack(stack *gtk.Stack) {
	var _arg0 *C.HdyViewSwitcher // out
	var _arg1 *C.GtkStack        // out

	_arg0 = (*C.HdyViewSwitcher)(unsafe.Pointer(externglib.InternObject(self).Native()))
	if stack != nil {
		_arg1 = (*C.GtkStack)(unsafe.Pointer(externglib.InternObject(stack).Native()))
	}

	C.hdy_view_switcher_set_stack(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(stack)
}
