// Code generated by girgen. DO NOT EDIT.

package handy

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/atk"
	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gtk/v3"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <handy.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.hdy_expander_row_get_type()), F: marshalExpanderRower},
	})
}

type ExpanderRow struct {
	_ [0]func() // equal guard
	PreferencesRow
}

var (
	_ gtk.Binner          = (*ExpanderRow)(nil)
	_ externglib.Objector = (*ExpanderRow)(nil)
)

func wrapExpanderRow(obj *externglib.Object) *ExpanderRow {
	return &ExpanderRow{
		PreferencesRow: PreferencesRow{
			ListBoxRow: gtk.ListBoxRow{
				Bin: gtk.Bin{
					Container: gtk.Container{
						Widget: gtk.Widget{
							InitiallyUnowned: externglib.InitiallyUnowned{
								Object: obj,
							},
							Object: obj,
							ImplementorIface: atk.ImplementorIface{
								Object: obj,
							},
							Buildable: gtk.Buildable{
								Object: obj,
							},
						},
					},
				},
				Object: obj,
				Actionable: gtk.Actionable{
					Widget: gtk.Widget{
						InitiallyUnowned: externglib.InitiallyUnowned{
							Object: obj,
						},
						Object: obj,
						ImplementorIface: atk.ImplementorIface{
							Object: obj,
						},
						Buildable: gtk.Buildable{
							Object: obj,
						},
					},
				},
			},
		},
	}
}

func marshalExpanderRower(p uintptr) (interface{}, error) {
	return wrapExpanderRow(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewExpanderRow creates a new ExpanderRow.
//
// The function returns the following values:
//
//    - expanderRow: new ExpanderRow.
//
func NewExpanderRow() *ExpanderRow {
	var _cret *C.GtkWidget // in

	_cret = C.hdy_expander_row_new()

	var _expanderRow *ExpanderRow // out

	_expanderRow = wrapExpanderRow(externglib.Take(unsafe.Pointer(_cret)))

	return _expanderRow
}

// AddAction adds an action widget to self.
//
// The function takes the following parameters:
//
//    - widget: action widget.
//
func (self *ExpanderRow) AddAction(widget gtk.Widgetter) {
	var _arg0 *C.HdyExpanderRow // out
	var _arg1 *C.GtkWidget      // out

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))
	_arg1 = (*C.GtkWidget)(unsafe.Pointer(widget.Native()))

	C.hdy_expander_row_add_action(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(widget)
}

// AddPrefix adds a prefix widget to self.
//
// The function takes the following parameters:
//
//    - widget: prefix widget.
//
func (self *ExpanderRow) AddPrefix(widget gtk.Widgetter) {
	var _arg0 *C.HdyExpanderRow // out
	var _arg1 *C.GtkWidget      // out

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))
	_arg1 = (*C.GtkWidget)(unsafe.Pointer(widget.Native()))

	C.hdy_expander_row_add_prefix(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(widget)
}

// EnableExpansion gets whether the expansion of self is enabled.
//
// The function returns the following values:
//
//    - ok: whether the expansion of self is enabled.
//
func (self *ExpanderRow) EnableExpansion() bool {
	var _arg0 *C.HdyExpanderRow // out
	var _cret C.gboolean        // in

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_expander_row_get_enable_expansion(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// The function returns the following values:
//
func (self *ExpanderRow) Expanded() bool {
	var _arg0 *C.HdyExpanderRow // out
	var _cret C.gboolean        // in

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_expander_row_get_expanded(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// IconName gets the icon name for self.
//
// The function returns the following values:
//
//    - utf8: icon name for self.
//
func (self *ExpanderRow) IconName() string {
	var _arg0 *C.HdyExpanderRow // out
	var _cret *C.gchar          // in

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_expander_row_get_icon_name(_arg0)
	runtime.KeepAlive(self)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))

	return _utf8
}

// ShowEnableSwitch gets whether the switch enabling the expansion of self is
// visible.
//
// The function returns the following values:
//
//    - ok: whether the switch enabling the expansion of self is visible.
//
func (self *ExpanderRow) ShowEnableSwitch() bool {
	var _arg0 *C.HdyExpanderRow // out
	var _cret C.gboolean        // in

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_expander_row_get_show_enable_switch(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Subtitle gets the subtitle for self.
//
// The function returns the following values:
//
//    - utf8 (optional): subtitle for self, or NULL.
//
func (self *ExpanderRow) Subtitle() string {
	var _arg0 *C.HdyExpanderRow // out
	var _cret *C.gchar          // in

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_expander_row_get_subtitle(_arg0)
	runtime.KeepAlive(self)

	var _utf8 string // out

	if _cret != nil {
		_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	}

	return _utf8
}

// UseUnderline gets whether an embedded underline in the text of the title and
// subtitle labels indicates a mnemonic. See
// hdy_expander_row_set_use_underline().
//
// The function returns the following values:
//
//    - ok: TRUE if an embedded underline in the title and subtitle labels
//      indicates the mnemonic accelerator keys.
//
func (self *ExpanderRow) UseUnderline() bool {
	var _arg0 *C.HdyExpanderRow // out
	var _cret C.gboolean        // in

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_expander_row_get_use_underline(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// SetEnableExpansion sets whether the expansion of self is enabled.
//
// The function takes the following parameters:
//
//    - enableExpansion: TRUE to enable the expansion.
//
func (self *ExpanderRow) SetEnableExpansion(enableExpansion bool) {
	var _arg0 *C.HdyExpanderRow // out
	var _arg1 C.gboolean        // out

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))
	if enableExpansion {
		_arg1 = C.TRUE
	}

	C.hdy_expander_row_set_enable_expansion(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(enableExpansion)
}

// The function takes the following parameters:
//
func (self *ExpanderRow) SetExpanded(expanded bool) {
	var _arg0 *C.HdyExpanderRow // out
	var _arg1 C.gboolean        // out

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))
	if expanded {
		_arg1 = C.TRUE
	}

	C.hdy_expander_row_set_expanded(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(expanded)
}

// SetIconName sets the icon name for self.
//
// The function takes the following parameters:
//
//    - iconName: icon name.
//
func (self *ExpanderRow) SetIconName(iconName string) {
	var _arg0 *C.HdyExpanderRow // out
	var _arg1 *C.gchar          // out

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))
	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(iconName)))
	defer C.free(unsafe.Pointer(_arg1))

	C.hdy_expander_row_set_icon_name(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(iconName)
}

// SetShowEnableSwitch sets whether the switch enabling the expansion of self is
// visible.
//
// The function takes the following parameters:
//
//    - showEnableSwitch: TRUE to show the switch enabling the expansion.
//
func (self *ExpanderRow) SetShowEnableSwitch(showEnableSwitch bool) {
	var _arg0 *C.HdyExpanderRow // out
	var _arg1 C.gboolean        // out

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))
	if showEnableSwitch {
		_arg1 = C.TRUE
	}

	C.hdy_expander_row_set_show_enable_switch(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(showEnableSwitch)
}

// SetSubtitle sets the subtitle for self.
//
// The function takes the following parameters:
//
//    - subtitle (optional): subtitle.
//
func (self *ExpanderRow) SetSubtitle(subtitle string) {
	var _arg0 *C.HdyExpanderRow // out
	var _arg1 *C.gchar          // out

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))
	if subtitle != "" {
		_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(subtitle)))
		defer C.free(unsafe.Pointer(_arg1))
	}

	C.hdy_expander_row_set_subtitle(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(subtitle)
}

// SetUseUnderline: if true, an underline in the text of the title and subtitle
// labels indicates the next character should be used for the mnemonic
// accelerator key.
//
// The function takes the following parameters:
//
//    - useUnderline: TRUE if underlines in the text indicate mnemonics.
//
func (self *ExpanderRow) SetUseUnderline(useUnderline bool) {
	var _arg0 *C.HdyExpanderRow // out
	var _arg1 C.gboolean        // out

	_arg0 = (*C.HdyExpanderRow)(unsafe.Pointer(self.Native()))
	if useUnderline {
		_arg1 = C.TRUE
	}

	C.hdy_expander_row_set_use_underline(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(useUnderline)
}
