// Code generated by girgen. DO NOT EDIT.

package handy

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/atk"
	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gtk/v3"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <handy.h>
import "C"

// glib.Type values for hdy-window-handle.go.
var GTypeWindowHandle = externglib.Type(C.hdy_window_handle_get_type())

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: GTypeWindowHandle, F: marshalWindowHandle},
	})
}

// WindowHandleOverrider contains methods that are overridable.
type WindowHandleOverrider interface {
}

type WindowHandle struct {
	_ [0]func() // equal guard
	gtk.EventBox
}

var (
	_ gtk.Binner = (*WindowHandle)(nil)
)

func classInitWindowHandler(gclassPtr, data C.gpointer) {
	C.g_type_class_add_private(gclassPtr, C.gsize(unsafe.Sizeof(uintptr(0))))

	goffset := C.g_type_class_get_instance_private_offset(gclassPtr)
	*(*C.gpointer)(unsafe.Add(unsafe.Pointer(gclassPtr), goffset)) = data

}

func wrapWindowHandle(obj *externglib.Object) *WindowHandle {
	return &WindowHandle{
		EventBox: gtk.EventBox{
			Bin: gtk.Bin{
				Container: gtk.Container{
					Widget: gtk.Widget{
						InitiallyUnowned: externglib.InitiallyUnowned{
							Object: obj,
						},
						Object: obj,
						ImplementorIface: atk.ImplementorIface{
							Object: obj,
						},
						Buildable: gtk.Buildable{
							Object: obj,
						},
					},
				},
			},
		},
	}
}

func marshalWindowHandle(p uintptr) (interface{}, error) {
	return wrapWindowHandle(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewWindowHandle creates a new WindowHandle.
//
// The function returns the following values:
//
//    - windowHandle: newly created WindowHandle.
//
func NewWindowHandle() *WindowHandle {
	var _cret *C.GtkWidget // in

	_cret = C.hdy_window_handle_new()

	var _windowHandle *WindowHandle // out

	_windowHandle = wrapWindowHandle(externglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _windowHandle
}
