// Code generated by girgen. DO NOT EDIT.

package handy

// #include <stdlib.h>
// #include <handy.h>
import "C"

// Init: call this function just after initializing GTK, if you are using
// Application it means it must be called when the #GApplication::startup signal
// is emitted. If libhandy has already been initialized, the function will
// simply return.
//
// This makes sure translations, types, themes, and icons for the Handy library
// are set up properly.
func Init() {
	C.hdy_init()
}
