// Code generated by girgen. DO NOT EDIT.

package handy

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/atk"
	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gtk/v3"
)

// #cgo pkg-config: libhandy-1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <glib-object.h>
// #include <handy.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.hdy_preferences_window_get_type()), F: marshalPreferencesWindower},
	})
}

type PreferencesWindow struct {
	Window
}

func wrapPreferencesWindow(obj *externglib.Object) *PreferencesWindow {
	return &PreferencesWindow{
		Window: Window{
			Window: gtk.Window{
				Bin: gtk.Bin{
					Container: gtk.Container{
						Widget: gtk.Widget{
							InitiallyUnowned: externglib.InitiallyUnowned{
								Object: obj,
							},
							ImplementorIface: atk.ImplementorIface{
								Object: obj,
							},
							Buildable: gtk.Buildable{
								Object: obj,
							},
							Object: obj,
						},
					},
				},
			},
		},
	}
}

func marshalPreferencesWindower(p uintptr) (interface{}, error) {
	return wrapPreferencesWindow(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewPreferencesWindow creates a new PreferencesWindow.
func NewPreferencesWindow() *PreferencesWindow {
	var _cret *C.GtkWidget // in

	_cret = C.hdy_preferences_window_new()

	var _preferencesWindow *PreferencesWindow // out

	_preferencesWindow = wrapPreferencesWindow(externglib.Take(unsafe.Pointer(_cret)))

	return _preferencesWindow
}

// CloseSubpage closes the current subpage to return back to the preferences, if
// there is no presented subpage, this does nothing.
func (self *PreferencesWindow) CloseSubpage() {
	var _arg0 *C.HdyPreferencesWindow // out

	_arg0 = (*C.HdyPreferencesWindow)(unsafe.Pointer(self.Native()))

	C.hdy_preferences_window_close_subpage(_arg0)
	runtime.KeepAlive(self)
}

// CanSwipeBack returns whether or not self allows switching from a subpage to
// the preferences via a swipe gesture.
func (self *PreferencesWindow) CanSwipeBack() bool {
	var _arg0 *C.HdyPreferencesWindow // out
	var _cret C.gboolean              // in

	_arg0 = (*C.HdyPreferencesWindow)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_preferences_window_get_can_swipe_back(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// SearchEnabled gets whether search is enabled for self.
func (self *PreferencesWindow) SearchEnabled() bool {
	var _arg0 *C.HdyPreferencesWindow // out
	var _cret C.gboolean              // in

	_arg0 = (*C.HdyPreferencesWindow)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_preferences_window_get_search_enabled(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// PresentSubpage sets subpage as the window's subpage and present it. The
// transition can be cancelled by the user, in which case visible child will
// change back to the previously visible child.
//
// The function takes the following parameters:
//
//    - subpage: subpage.
//
func (self *PreferencesWindow) PresentSubpage(subpage gtk.Widgetter) {
	var _arg0 *C.HdyPreferencesWindow // out
	var _arg1 *C.GtkWidget            // out

	_arg0 = (*C.HdyPreferencesWindow)(unsafe.Pointer(self.Native()))
	_arg1 = (*C.GtkWidget)(unsafe.Pointer(subpage.Native()))

	C.hdy_preferences_window_present_subpage(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(subpage)
}

// SetCanSwipeBack sets whether or not self allows switching from a subpage to
// the preferences via a swipe gesture.
//
// The function takes the following parameters:
//
//    - canSwipeBack: new value.
//
func (self *PreferencesWindow) SetCanSwipeBack(canSwipeBack bool) {
	var _arg0 *C.HdyPreferencesWindow // out
	var _arg1 C.gboolean              // out

	_arg0 = (*C.HdyPreferencesWindow)(unsafe.Pointer(self.Native()))
	if canSwipeBack {
		_arg1 = C.TRUE
	}

	C.hdy_preferences_window_set_can_swipe_back(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(canSwipeBack)
}

// SetSearchEnabled sets whether search is enabled for self.
//
// The function takes the following parameters:
//
//    - searchEnabled: TRUE to enable search, FALSE to disable it.
//
func (self *PreferencesWindow) SetSearchEnabled(searchEnabled bool) {
	var _arg0 *C.HdyPreferencesWindow // out
	var _arg1 C.gboolean              // out

	_arg0 = (*C.HdyPreferencesWindow)(unsafe.Pointer(self.Native()))
	if searchEnabled {
		_arg1 = C.TRUE
	}

	C.hdy_preferences_window_set_search_enabled(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(searchEnabled)
}
