// Code generated by girgen. DO NOT EDIT.

package handy

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/atk"
	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gtk/v3"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <handy.h>
import "C"

// glib.Type values for hdy-title-bar.go.
var GTypeTitleBar = externglib.Type(C.hdy_title_bar_get_type())

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: GTypeTitleBar, F: marshalTitleBar},
	})
}

// TitleBarOverrider contains methods that are overridable.
type TitleBarOverrider interface {
}

type TitleBar struct {
	_ [0]func() // equal guard
	gtk.Bin
}

var (
	_ gtk.Binner = (*TitleBar)(nil)
)

func classInitTitleBarrer(gclassPtr, data C.gpointer) {
	C.g_type_class_add_private(gclassPtr, C.gsize(unsafe.Sizeof(uintptr(0))))

	goffset := C.g_type_class_get_instance_private_offset(gclassPtr)
	*(*C.gpointer)(unsafe.Add(unsafe.Pointer(gclassPtr), goffset)) = data

}

func wrapTitleBar(obj *externglib.Object) *TitleBar {
	return &TitleBar{
		Bin: gtk.Bin{
			Container: gtk.Container{
				Widget: gtk.Widget{
					InitiallyUnowned: externglib.InitiallyUnowned{
						Object: obj,
					},
					Object: obj,
					ImplementorIface: atk.ImplementorIface{
						Object: obj,
					},
					Buildable: gtk.Buildable{
						Object: obj,
					},
				},
			},
		},
	}
}

func marshalTitleBar(p uintptr) (interface{}, error) {
	return wrapTitleBar(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewTitleBar creates a new TitleBar.
//
// The function returns the following values:
//
//    - titleBar: new TitleBar.
//
func NewTitleBar() *TitleBar {
	var _cret *C.GtkWidget // in

	_cret = C.hdy_title_bar_new()

	var _titleBar *TitleBar // out

	_titleBar = wrapTitleBar(externglib.Take(unsafe.Pointer(_cret)))

	return _titleBar
}

// SelectionMode returns whether whether self is in selection mode.
//
// The function returns the following values:
//
//    - ok: TRUE if the title bar is in selection mode.
//
func (self *TitleBar) SelectionMode() bool {
	var _arg0 *C.HdyTitleBar // out
	var _cret C.gboolean     // in

	_arg0 = (*C.HdyTitleBar)(unsafe.Pointer(externglib.InternObject(self).Native()))

	_cret = C.hdy_title_bar_get_selection_mode(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// SetSelectionMode sets whether self is in selection mode.
//
// The function takes the following parameters:
//
//    - selectionMode: TRUE to enable the selection mode.
//
func (self *TitleBar) SetSelectionMode(selectionMode bool) {
	var _arg0 *C.HdyTitleBar // out
	var _arg1 C.gboolean     // out

	_arg0 = (*C.HdyTitleBar)(unsafe.Pointer(externglib.InternObject(self).Native()))
	if selectionMode {
		_arg1 = C.TRUE
	}

	C.hdy_title_bar_set_selection_mode(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(selectionMode)
}
