// Code generated by girgen. DO NOT EDIT.

package handy

import (
	"runtime"
	"unsafe"

	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #cgo pkg-config: libhandy-1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <glib-object.h>
// #include <handy.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.hdy_enum_value_object_get_type()), F: marshalEnumValueObjector},
	})
}

type EnumValueObject struct {
	*externglib.Object
}

var (
	_ externglib.Objector = (*EnumValueObject)(nil)
)

func wrapEnumValueObject(obj *externglib.Object) *EnumValueObject {
	return &EnumValueObject{
		Object: obj,
	}
}

func marshalEnumValueObjector(p uintptr) (interface{}, error) {
	return wrapEnumValueObject(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

func (self *EnumValueObject) Name() string {
	var _arg0 *C.HdyEnumValueObject // out
	var _cret *C.gchar              // in

	_arg0 = (*C.HdyEnumValueObject)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_enum_value_object_get_name(_arg0)
	runtime.KeepAlive(self)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))

	return _utf8
}

func (self *EnumValueObject) Nick() string {
	var _arg0 *C.HdyEnumValueObject // out
	var _cret *C.gchar              // in

	_arg0 = (*C.HdyEnumValueObject)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_enum_value_object_get_nick(_arg0)
	runtime.KeepAlive(self)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))

	return _utf8
}

func (self *EnumValueObject) Value() int {
	var _arg0 *C.HdyEnumValueObject // out
	var _cret C.gint                // in

	_arg0 = (*C.HdyEnumValueObject)(unsafe.Pointer(self.Native()))

	_cret = C.hdy_enum_value_object_get_value(_arg0)
	runtime.KeepAlive(self)

	var _gint int // out

	_gint = int(_cret)

	return _gint
}
