// Code generated by girgen. DO NOT EDIT.

package handy

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/gtk/v3"
)

// #cgo pkg-config: libhandy-1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <handy.h>
import "C"

// EaseOutCubic computes the ease out for t.
//
// The function takes the following parameters:
//
//    - t: term.
//
func EaseOutCubic(t float64) float64 {
	var _arg1 C.gdouble // out
	var _cret C.gdouble // in

	_arg1 = C.gdouble(t)

	_cret = C.hdy_ease_out_cubic(_arg1)
	runtime.KeepAlive(t)

	var _gdouble float64 // out

	_gdouble = float64(_cret)

	return _gdouble
}

// GetEnableAnimations returns whether animations are enabled for that widget.
// This should be used when implementing an animated widget to know whether to
// animate it or not.
//
// The function takes the following parameters:
//
//    - widget: Widget.
//
func GetEnableAnimations(widget gtk.Widgetter) bool {
	var _arg1 *C.GtkWidget // out
	var _cret C.gboolean   // in

	_arg1 = (*C.GtkWidget)(unsafe.Pointer(widget.Native()))

	_cret = C.hdy_get_enable_animations(_arg1)
	runtime.KeepAlive(widget)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}
